# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "lit"
        update-types: ["version-update:semver-major"]
    groups:
      eslint:
        patterns:
          - "eslint"
          - "@typescript-eslint/*"
          - "eslint-*"
      rollup:
        patterns:
          - "rollup"
          - "@rollup/*"
      types:
        patterns:
          - "@types/*"
